name: CI/CD dengan Selenium & DAST

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable unzip wget

      - name: Setup ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest webdriver-manager

      - name: Run Selenium tests
        run: pytest --maxfail=5 --disable-warnings -v

  dast:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Run DAST (Dynamic Application Security Testing)
        run: echo "DAST testing goes here"
